[package]
name = "pumicite"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
  "crates/*",
]

[dependencies]
pumicite_types = { path = "./crates/types" }
ash = { git = "https://github.com/0xbeefd1ed/ash", branch = "meta" }
tracing = "0.1"
vk-mem = { git = "https://github.com/gwihlidal/vk-mem-rs.git", branch = "bump-ash" }
glam = "0.30"
raw-window-handle = "0.6"
smallvec = "1.15"
bitvec = "1"
log = { version = "0.4", features = ["kv"] }
serde = { version = "1", features = ["derive"] }
crossbeam-channel = "0.5"
portable-atomic = "1.5"
event-listener = "5"
blocking = "1.6"
pin-project-lite = "0.2"

bevy_ecs = { version = "0.18.1", optional = true }
bevy_asset = { version = "0.18.1", optional = true }
bevy_reflect = { version = "0.18.1", optional = true }

[features]
bevy = ["bevy_ecs", "bevy_asset", "bevy_reflect"]

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
raw-window-metal = "0.4"

[patch."https://github.com/ash-rs/ash.git"]
ash = { git = "https://github.com/0xbeefd1ed/ash", branch = "meta" }

[dev-dependencies]
bytemuck = "1.23"
bevy = { version = "0.18.1", default-features=false, features=["bevy_winit", "bevy_log", "bevy_asset", "file_watcher", "multi_threaded", "bevy_scene"] }
bevy_pumicite = { path = "./crates/bevy" }
pumicite_egui = { path = "./crates/egui" }
pumicite_scene = { path = "./crates/scene" }
