[package]
name = "pumicite_egui"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_ecs = { version = "0.18.1" }
bevy_app = { version = "0.18.1" }
bevy_window = { version = "0.18.1" }
bevy_asset = { version = "0.18.1" }
glam = "0.30"
pumicite = { path = "../../" }
bevy_pumicite = { path = "../bevy" }
bytemuck = "1.23"
tracing = "0.1"

[dependencies.bevy_egui]
version = "0.39.1"
default-features = false
features = ["manage_clipboard", "open_url", "default_fonts"]
